// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSv7EPtsxVYK02K0PPwRKQDfieO1DXCB8',
    appId: '1:572406151179:web:7eb6de5ac187e7e869ef0e',
    messagingSenderId: '572406151179',
    projectId: 'coach-hub-app-522cd',
    authDomain: 'coach-hub-app-522cd.firebaseapp.com',
    storageBucket: 'coach-hub-app-522cd.firebasestorage.app',
    measurementId: 'G-RRZE0F78FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9p0tIFxzDOCg8W2l2NuohNAddt5gGVQU',
    appId: '1:572406151179:android:be3ddad0f18e0cd569ef0e',
    messagingSenderId: '572406151179',
    projectId: 'coach-hub-app-522cd',
    storageBucket: 'coach-hub-app-522cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdgEPhj0kt9Tq2nTK2BQVLsRBZjBO2UAA',
    appId: '1:572406151179:ios:170d1f8679c9404269ef0e',
    messagingSenderId: '572406151179',
    projectId: 'coach-hub-app-522cd',
    storageBucket: 'coach-hub-app-522cd.firebasestorage.app',
    iosClientId: '572406151179-3rhod5iq4a3ttsonhj0kj8a96otl2thb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdgEPhj0kt9Tq2nTK2BQVLsRBZjBO2UAA',
    appId: '1:572406151179:ios:170d1f8679c9404269ef0e',
    messagingSenderId: '572406151179',
    projectId: 'coach-hub-app-522cd',
    storageBucket: 'coach-hub-app-522cd.firebasestorage.app',
    iosClientId: '572406151179-3rhod5iq4a3ttsonhj0kj8a96otl2thb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSv7EPtsxVYK02K0PPwRKQDfieO1DXCB8',
    appId: '1:572406151179:web:cd722fd62da191e569ef0e',
    messagingSenderId: '572406151179',
    projectId: 'coach-hub-app-522cd',
    authDomain: 'coach-hub-app-522cd.firebaseapp.com',
    storageBucket: 'coach-hub-app-522cd.firebasestorage.app',
    measurementId: 'G-REZJ51CY76',
  );
}
